BART_STATIONS = [
    ('12th St. Oakland City Center BART Station', '12th St. Oakland City Center Station, Oakland, CA 94607, USA'),
    ('16th St. Mission (SF) BART Station', '16th St Mission, Qa, 2000 Mission St, San Francisco, CA 94110, USA'),
    ('19th St. Oakland BART Station', '19th St / Oakland, 1900 Broadway, Oakland, CA 94612, USA'),
    ('24th St. Mission (SF) BART Station', '24th St Mission, 2800 Mission St, San Francisco, CA 94110, USA'),
    ('Antioch BART Station', 'Antioch BART, 1600 Slatten Ranch Rd, Antioch, CA 94509, USA'),
    ('Ashby (Berkeley) BART Station', 'Ashby Station, 3100 Adeline St, Berkeley, CA 94703, USA'),
    ('Balboa Park (SF) BART Station', 'Balboa Park Station, 401 Geneva Ave, San Francisco, CA 94112, USA'),
    ('Bay Fair (San Leandro) BART Station', 'Bay Fair, 15242 Hesperian Blvd, San Leandro, CA 94578, USA'),
    ('Castro Valley BART Station', 'Castro Valley BART Station, Castro Valley, CA 94546, USA'),
    ('Civic Center / UN Plaza BART Station', 'Civic Center, 1150 Market St, San Francisco, CA 94102, USA'),
    ('Coliseum BART Station', 'Coliseum Station, 7200 San Leandro St, Oakland, CA 94621, USA'),
    ('Colma BART Station', 'Colma Station, 365 D St, Colma, CA 94014, USA'),
    ('Concord BART Station', 'Concord Station, 1451 Oakland Ave, Concord, CA 94520, USA'),
    ('Daly City BART Station', 'Daly City Bart Station, Daly City, CA 94014, USA'),
    ('Downtown Berkeley BART Station', 'Downtown Berkeley Station, 2160 Shattuck Ave, Berkeley, CA 94704, USA'),
    ('Dublin / Pleasanton BART Station', 'Dublin / Pleasanton BART Station, 5801 Owens Dr, Pleasanton, CA 94588, USA'),
    ('El Cerrito del Norte BART Station', 'El Cerrito del Norte Station, 6400 Cutting Blvd, El Cerrito, CA 94530, USA'),
    ('El Cerrito Plaza BART Station', 'El Cerrito Plaza, 6699 Fairmount Ave, El Cerrito, CA 94530, USA'),
    ('Embarcadero (SF) BART Station', 'Embarcadero, San Francisco, CA 94111, USA'),
    ('Fremont BART Station', 'Fremont, 2000 Bart Way, Fremont, CA 94536, USA'),
    ('Fruitvale (Oakland) BART Station', 'Fruitvale Station, 3401 E 12th St, Oakland, CA 94601, USA'),
    ('Glen Park (SF) BART Station', 'Glen Park Station, 2901 Diamond St, San Francisco, CA 94131, USA'),
    ('Hayward BART Station', 'South Hayward BART Station, 28601 Dixon St, Hayward, CA 94544, USA'),
    ('Lafayette BART Station', 'Lafayette, 3601 Deer Hill Rd, Lafayette, CA 94549, USA'),
    ('Lake Merritt (Oakland) BART Station', 'Lake Merritt, 800 Oak St, Oakland, CA 94607, USA'),
    ('MacArthur (Oakland) BART Station', 'MacArthur, 555 40th St, Oakland, CA 94609, USA'),
    ('Millbrae BART Station', 'Millbrae, 200 Rollins Rd, Millbrae, CA 94030, USA'),
    ('Montgomery St. (SF) BART Station', 'Montgomery Street, 598 Market St, San Francisco, CA 94104, USA'),
    ('North Berkeley BART Station', 'North Berkeley, 1750 Sacramento St, Berkeley, CA 94702, USA'),
    ('North Concord / Martinez BART Station', 'North Concord/Martinez Station, 3700 Port Chicago Hwy, Concord, CA 94520, USA'),
    ('Oakland International Airport BART Station', 'Oakland International Airport Station, Oakland, CA 94621, USA'),
    ('Orinda BART Station', 'Orinda, 11 Camino Pablo, Orinda, CA 94563, USA'),
    ('Pittsburg / Bay Point BART Station', 'Pittsburg/Bay Point BART Station, Pittsburg, CA 94565, USA'),
    ('Pittsburg Center BART Station', 'Pittsburg Center, 2099 Railroad Ave, Pittsburg, CA 94565, USA'),
    ('Pleasant Hill / Contra Costa Centre BART Station', 'Pleasant Hill/Contra Costa Centre, 1365 Treat Blvd, Walnut Creek, CA 94597, USA'),
    ('Powell St. (SF) BART Station', 'Powell Street Station, 899 Market St, San Francisco, CA 94103, USA'),
    ('Richmond BART Station', 'Richmond, 1700 Nevin Ave, Richmond, CA 94801, USA'),
    ('Rockridge (Oakland) BART Station', 'Rockridge Station, 5660 College Ave, Oakland, CA 94618, USA'),
    ('San Bruno BART Station', 'San Bruno, 1151 Huntington Ave, San Bruno, CA 94066, USA'),
    ('San Francisco International Airport BART Station', 'San Francisco International Airport Station, San Francisco, CA 94128, USA'),
    ('San Leandro BART Station', 'San Leandro Station, 1401 San Leandro Blvd, San Leandro, CA 94577, USA'),
    ('South Hayward BART Station', 'South Hayward BART Station, 28601 Dixon St, Hayward, CA 94544, USA'),
    ('South San Francisco BART Station', 'South San Francisco Station, 1333 Mission Rd, South San Francisco, CA 94080, USA'),
    ('Union City BART Station', 'Union City BART Stop 1, Union City, CA 94587, USA'),
    ('Walnut Creek BART Station', 'Walnut Creek Station, 200 Ygnacio Valley Rd, Walnut Creek, CA 94596, USA'),
    ('Warm Springs / South Fremont BART Station', 'Warm Springs / South Fremont Station, 45193 Warm Springs Blvd, Fremont, CA 94539, USA'),
    ('West Dublin / Pleasanton BART Station', 'West Dublin/Pleasanton, 6501 Golden Gate Dr, Dublin, CA 94568, USA'),
    ('West Oakland BART Station', 'West Oakland Station, 1451 7th St, Oakland, CA 94607, USA')
]