BART_STATIONS = [
    "12th St. Oakland City Center BART Station",
    "16th St. Mission (SF) BART Station",
    "19th St. Oakland BART Station",
    "24th St. Mission (SF) BART Station",
    "Antioch BART Station",
    "Ashby (Berkeley) BART Station",
    "Balboa Park (SF) BART Station",
    "Bay Fair (San Leandro) BART Station",
    "Castro Valley BART Station",
    "Civic Center / UN Plaza BART Station",
    "Coliseum BART Station",
    "Colma BART Station",
    "Concord BART Station",
    "Daly City BART Station",
    "Downtown Berkeley BART Station",
    "Dublin / Pleasanton BART Station",
    "El Cerrito del Norte BART Station",
    "El Cerrito Plaza BART Station",
    "Embarcadero (SF) BART Station",
    "Fremont BART Station",
    "Fruitvale (Oakland) BART Station",
    "Glen Park (SF) BART Station",
    "Hayward BART Station",
    "Lafayette BART Station",
    "Lake Merritt (Oakland) BART Station",
    "MacArthur (Oakland) BART Station",
    "Millbrae BART Station",
    "Montgomery St. (SF) BART Station",
    "North Berkeley BART Station",
    "North Concord / Martinez BART Station",
    "Oakland International Airport BART Station",
    "Orinda BART Station",
    "Pittsburg / Bay Point BART Station",
    "Pittsburg Center BART Station",
    "Pleasant Hill / Contra Costa Centre BART Station",
    "Powell St. (SF) BART Station",
    "Richmond BART Station",
    "Rockridge (Oakland) BART Station",
    "San Bruno BART Station",
    "San Francisco International Airport BART Station",
    "San Leandro BART Station",
    "South Hayward BART Station",
    "South San Francisco BART Station",
    "Union City BART Station",
    "Walnut Creek BART Station",
    "Warm Springs / South Fremont BART Station",
    "West Dublin / Pleasanton BART Station",
    "West Oakland BART Station",
]
